### ISSUE TITLE
Rename to School of Data Handbook (?)

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook#10]
Several suggestions for rename here:
- Data Handbook
- Open Data Handbook / Data (section)
- School of Data Handbook

After talking with people I suggest going with latter -- it's closest to immediate use of the handbook, ties to a bigger project and does not engender confusion with Open Data Handbook as first two do.

**Comment by lauranewman** [comment]
I could go with that. Another option might be Data Wrangling Handbook / The Data Wrangler's Handbook. That ties in with School of Data stuff, without any sense of being 'only' for the School of Data. Happy with either though.

**Comment by rufuspollock** [comment]
I like Data Wrangler's handbook too (and datawrangling.org is available ...). It would also help cement the term and make the handbook somewhat independent of the SoD (conversely the association could be good)

@pudo: what's your thoughts here? Options (in terms of domains)
- handbook.schoolofdata.org
- datawrangling.org
- opendatahandbook.org/datawrangling/

@danielabsilva: I know you suggested School of Data handbook over data patterns or opendatahandbook/data. What do you think of Data Wrangler's Handbook or similar?

**Comment by pudo** [comment]
I like Data Wrangler's Handbook as a title, but as you know I'm very partial to domain name 3) :)

**Comment by rufuspollock** [comment]
@pudo - you mean the subdomain? I agree though in the first instance, for convenience i think we host on readthedocs (and hence at some other domain) until we have sorted out exactly how to do that.

OK: so at the moment I feel agreement coming on. As an immediate action I suggest we:
- Rename this repo to datawranglerhandbook (or datawrangling?)
- Redirect datapatterns.org to handbook.schoolofdata.org (unless we sort out datapatterns to point to rtfd)
- Make necessary name changes

Does this sound correct / sensible?

**Comment by pudo** [comment]
Hm, I still feel the additional domain name will do us no good, but go ahead :)

**Comment by rufuspollock** [comment]
WONTFIX.

We are currently settled on http://handbook.schoolofdata.org/ for location and Data Wrangling Handbook for main name. There is a possibility of further relocation (to opendatahandbook.org/{suburl}) at some later date but that is not decided as yet.
