### ISSUE TITLE
Permalinks in tutorials are wrong 

### ISSUE THREAD

**Issue by gsilvapt** [okfn/handbook#100]
In the `/core-guides/index.md`, the text that is trying to recommend the reading of the `data-guides` is currently forwarding to `/core-guides/data-guides`, causing an error. It should forward to `/data-guides` directory.

Code used: `[[text]](data-guides/)` - this is potentially wrong.

**Comment by Anterotesis** [comment]
Not sure which pages you are referring to, but this issue applies to the last three links on this page:
http://okfnlabs.org/handbook/core-guides/
Namely these links are broken:
Working with GitHub
Core Datasets Roadmap
Your first package

**Comment by gsilvapt** [comment]
@Anterotesis: those pages haven't been yet created, thus is shows a 404 error. If you read through the introduction texts to core-guide, you will find that some links are not working, namely those that recommend the reading of the data guides.

**Comment by gsilvapt** [comment]
This can be solved if we point the path correctly. 

`[text](/path/to/file/filename)` is the correct code, and not just `[text](filename)`. The last form will perform differently.

The to-do list here is to update all entries that do not have a matching URL pattern. However, this still depends on the product structure, which is being discussed in issues #90 and #94.
