### ISSUE TITLE
[super] Data guide section

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook#102]
- [x] `/data/` basic page - "data wrangling guide" - can we reuse old patterns home page? - #104
- [x] `/data/tutorial/`\- #105
- [x] `/data/patterns/` - move all existing patterns under here - #103

**Comment by gsilvapt** [comment]
@rgrp can we close this issue too? All of its sub-items seem ready/fixed.

**Comment by rufuspollock** [comment]
FIXED.
