### ISSUE TITLE
Move old patterns to /data/patterns/

### ISSUE THREAD

**Issue by gsilvapt** [okfn/handbook#103]
Other things related with the organization should be discussed here, specially when it comes to guides related with patterns.
- [X] Move the list of patterns as per https://github.com/okfn/handbook/tree/ae934ab2efac136979a3765cf01ffae96fbc0e74/pattern from `/data-guides/` to `/data/patterns/`
-  [x] Rewrite the following files: `glossary.md`, `index.md`, `intro.md` - copy from the previous version?

**Comment by rufuspollock** [comment]
@gsilvapt great - could you detail with bullet points in the description the steps involved and any changes.

**Comment by rufuspollock** [comment]
@gsilvapt why do we need to do rewriting? And the "?" at end suggests you were unsure.

**Comment by gsilvapt** [comment]
@rgrp Those files were the ones missing in the old directory. They either were merged or renamed, so I had to restore that. If any, `index.md` is needed because of the function of the index file in a directory functioning as a page. I suggested copying from the other versions to avoid writing everything from scratch. It was a suggestion, hence yes, I was unsure whether we get these contents from an older version or not.

**Comment by rufuspollock** [comment]
@gsilvapt has moved the pages but at least the index page is broken as none of the links work:

http://okfnlabs.org/handbook/data/patterns/

Want to generate those links automatically probably using jekyll to walk through the list of pages ...

**Comment by gsilvapt** [comment]
FIXED.

**Comment by rufuspollock** [comment]
FIXED.
