### ISSUE TITLE
Data Wrangling Tutorial

### ISSUE THREAD

**Issue by gsilvapt** [okfn/handbook#105]
As suggestion, it would be interesting to use the [Historical GDP](https://github.com/gsilvapt/historical-data) as a walk-through to fit under the Data Wrangling Guide.

The Data Wrangling tutorial could have a structure that answers specifically:
- What kind of things we do
- What skills are needed

All of this would fit under the "Data Wrangling Guide" - #89 

---

The walk-through content and to-do list:
- How to Get Data - Tell users how can they get data to use for a data package, from World Bank's API and from a Spreadsheet
- Cleaning Up Data - After getting the data, what kind of details should you be looking at to make sure all packages follow the same structure and principles (I can only show some tips & tricks with Python)
- What is next? - Reference to core datasets project, mentioning there is lots of data wrangling to be done

---

Dir structure, as per #102. 

`/data/`
`/data/tutorial`

The content of the walk-through should go under the tutorial directory.

**Comment by rufuspollock** [comment]
@gsilvapt could you flesh what you think the structure of this would be e.g. give section headings and a short sentence or two.

**Comment by gsilvapt** [comment]
If PR #116 is accepted, this issue is fixed.

To be closed soon.

**Comment by rufuspollock** [comment]
FIXED.
