### ISSUE TITLE
Update Liberating HTML Data Tables with Planets Example

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook#11]
@danielabsilva  As per earlier discussion :-)

Would be great to update / enhance the Liberating HTML Data Tables entry with the Planets example - http://handbook.schoolofdata.org/en/latest/liberating-html-tables.html (source: https://github.com/okfn/datapatterns/blob/master/text/liberating-html-tables.rst) 

E.g. create section Scraping the Size of Planets from NASA using Google Docs

Alternatively we could create a completely new item :-)

**Comment by mihi-tr** [comment]
@rgrp is this still an actual issue? the file linked moved to: http://handbook.schoolofdata.org/en/latest/part4/recipes/liberating-html-tables.html
