### ISSUE TITLE
Rename DataPatterns to Data Wranglers Handbook

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook#12]

**Comment by lauranewman** [comment]
Technically, this should probably be Data Wrangler's Handbook - although obviously not for web addresses etc. Not a major issue I think.

**Comment by rufuspollock** [comment]
Or Data Wranglers'

**Comment by lauranewman** [comment]
Yep, even better.

**Comment by johnapaz** [comment]
I think this issue can be closed, no? Current title: "Data Wrangling Handbook." Please advise.

**Comment by rufuspollock** [comment]
@johnapaz quite right. Closing now.
