### ISSUE TITLE
As a contributor and user of the Data Wrangling Handbook, I would like a "last edited" or "last updated" field. 

### ISSUE THREAD

**Issue by johnapaz** [okfn/handbook#13]
A small field at the top that shows the last date of edit so users are aware of how old/new the information is. Or some other display field to show which version is being viewed.

**Comment by rufuspollock** [comment]
@johnapaz is this per page or for the entire handbook. Imagine the former is more useful.

**Comment by johnapaz** [comment]
@rgrp I agree, per page (or per section maybe) is definitely more useful. But, to start, an over all high-level "last updated" field on the main page would be useful for passersby or for those only peripherally interested.

**Comment by rufuspollock** [comment]
Looks like we want http://sphinx.pocoo.org/config.html#confval-html_last_updated_fmt (the handbook is built in sphinx). Will look into getting this added!

**Comment by mihi-tr** [comment]
Done (16dcf2d582139896b3c2d7672116e28387ff1ab1)

**Comment by johnapaz** [comment]
Wonderful!
