### ISSUE TITLE
Host on readthedocs.org

### ISSUE THREAD

**Issue by pudo** [okfn/handbook#2]
Seems like they have free GitHub webhooks and provide an excellent service - why not use it for this?

**Comment by arnim** [comment]
Its a nice place to push docs to, but I guess they have already found something... DataPatterns.ORG

**Comment by rufuspollock** [comment]
Issue with readthedocs are:
- We already have something working with s3
- The slightly annoying /en/latest prefixed to every url on RTD
- Lack of submodule support (very useful for reusable themes) -- see my issue on this https://github.com/rtfd/readthedocs.org/issues/149

Thus, at the present time I'd like to close this as wontfix.

**Comment by rufuspollock** [comment]
ReadTheDocs actually seems like a reasonable solution and auto-updater for current solution no longer works so I think this is the moment to move there. One issue is that you need something cname-able for RTD. I therefore may run it as handbook.schoolofdata.org for the present (cf #10).

**Comment by rufuspollock** [comment]
FIXED. Moved to readthedocs 1m+ ago.
