### ISSUE TITLE
html theme?

### ISSUE THREAD

**Issue by mihi-tr** [okfn/handbook#21]
Trying to make html.

make html
sphinx-build -b html -d build/doctrees   text build/html
Making output directory...
Running Sphinx v1.1.3
loading pickled environment... not yet created

Theme error:
no theme named 'sphinx-theme-okfn' found (missing theme.conf?)

---

Is this intended or is the theme file just missing?

**Comment by rufuspollock** [comment]
@mihi-tr you just need to do:

```
git submodule init 
git submodule update
```

**Comment by rufuspollock** [comment]
That _should_ be in the README - apologies!

**Comment by rufuspollock** [comment]
cf #22 which is now closed and new README!
