### ISSUE TITLE
Fixed header bar obscures glossary text

### ISSUE THREAD

**Issue by lauranewman** [okfn/handbook#27]
Because the fixed header bar partially obscures the page, when you click on a term and are redirected to the glossary, the term is entirely obscured beneath the header bar (e.g. if you want to see the definition of API, the first term that will appear is Attribution License). 

Possible fixes:
- Configure the header bar differently, so that glossary terms would be displayed below it
- Get rid of the header bar

**Comment by mihi-tr** [comment]
This is an issue of https://github.com/okfn/sphinx-theme-okfn see https://github.com/okfn/sphinx-theme-okfn/issues/20 the sphinx-theme people seem to be unwilling to fix this, I'll see what I can do.

**Comment by mihi-tr** [comment]
fixed in https://github.com/mihi-tr/sphinx-theme-okfn/commit/f421a88af59b8630f9935afac5c596663155375f waiting for the change to be pulled into the main repo. then it'll update with the website.
