### ISSUE TITLE
Dealing with ASPX 

### ISSUE THREAD

**Issue by h4ck3rm1k3** [okfn/handbook#3]
https://launchpad.net/aspxezxs here is code I have in production to extract data from evil microsoft aspx .net web databases, it manages the funky special encrypted parameters for screen scraping and is extensible.

**Comment by h4ck3rm1k3** [comment]
Also, you should mention using archive.org for hosting data, also https://github.com/infochimps/chimps you should mention.

**Comment by timClicks** [comment]
Thanks for your contribution. This is excellent. 

It seems `aspxezxs` is a Perl based tool, but the rest of our code is in Python. I guess this doesn't matter too much because `aspxezxs` is standalone and can be called from Python scripts.

Please add the hosting options as another issue.

**Comment by timClicks** [comment]
ScraperWiki has a great tutorial/example of scraping [ASPX pages](http://scraperwiki.com/scrapers/new/python?template=advanced-scraping-aspx-pages)

**Comment by h4ck3rm1k3** [comment]
Oh, interesting, well we have started to work on a reporting tool in python, it it not done yet.
If it is so easy to do this in python with the viewstate, i would be interested.. in any case the perl script works. see also the makefile for running parallel jobs for downloading many databases.

**Comment by rufuspollock** [comment]
OUTOFDATE
