### ISSUE TITLE
Move http://handbook.schoolofdata.org to http://schoolofdata.org/handbook

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook#31]
Move the handbook from subdomain to suburl. We'd still use sphinx but we'd use Wordpress API to push built sphinx docs up into wordpress.

Benefits:
- Integrated experience
- Shared theming
- Nicer urls!

Costs:
- Some coding effort
- Ongoing maintenance (site won't automatically rebuild as it does via
  readthedocs)
## How to

Use pywordpress and wordpress XML API

Here's a library to help with this: https://github.com/rgrp/pywordpress

Here's an example of this to create multiple pages: https://bitbucket.org/okfn/sysadmin/src/c4f455c12f85/bin/misc.py?at=default

**Comment by mihi-tr** [comment]
Done! the handbook lives now on http://schoolofdata.org/handbook/ 

thanks for the code! works even nicer with pyquery.

**Comment by rufuspollock** [comment]
Seem to have an issue with trailing space and/or <br /> in the paragraphs - see http://schoolofdata.org/handbook/introduction/. Need to fix and re-upload (?)

**Comment by mihi-tr** [comment]
indeed. haven't noticed that one.
