### ISSUE TITLE
Additional search engines for raw data

### ISSUE THREAD

**Issue by jgrethe** [okfn/handbook#39]
I was reading through the handbook and would like to offer another search engine for raw data (http://schoolofdata.org/handbook/recipes/howtogetdata/):

Neuroscience Information Framework
http://neuinfo.org

The Neuroscience Information Framweork (NIF) is a biological search engine that searches the contents of more than 150 databases relevant to neuroscience and the biomedical literature simultaneously that enables researchers, students and educators to pull together information about the nervous system.

**Comment by mihi-tr** [comment]
I think it'll be good to collect those in a list of resources. We've started this as part of the School of Data here: http://schoolofdata.org/datasources/ 

Added your link

**Comment by rufuspollock** [comment]
@mihi-tr can I suggest using http://okfnlabs.org/listify/ - you could use it with a spreadsheet based off a google form too ...

(Can explain a bit more if you are around online!)

**Comment by mihi-tr** [comment]
@rgrp will check this - in the meanwhile the list view works quite well...

**Comment by mihi-tr** [comment]
@rgrp done...
