### ISSUE TITLE
Transcribe: Basic Analysis

### ISSUE THREAD

**Issue by mihi-tr** [okfn/handbook#43]
Transcribe the following module to restructured text.

Instructions here: https://github.com/okfn/datawrangling/wiki/Tutorial-Sprint
Module: https://docs.google.com/document/d/1O1LHqnwy8narzwW2N1nUTlVEqL1cN-y88rXDgXfvYzc/edit#heading=h.eudisn49u2hw

**Comment by icedwater** [comment]
How do I assign myself here?

**Comment by mihi-tr** [comment]
You can either comment or use the assignment function up top.

**Comment by rufuspollock** [comment]
@icedwater you assign yourself just by commenting as you did :-) Consider yourself hereby assigned :-)

**Comment by brylie** [comment]
I converted the text, but found that embedding the images hosted on a Flickr account may violate the Flickr Community Guidelines.

> The direct link to a photo file is no longer shown on the page. Per the Flickr Community Guidelines "pages on other websites that display content hosted on flickr.com must provide a link from each photo or video back to its page on Flickr." Linking directly to the photo file doesn't do this. 
> http://www.flickr.com/guidelines.gne

**Comment by icedwater** [comment]
This is true. I didn't know this about Flickr. I also converted the text but couldn't find the first picture -_-

**Comment by rufuspollock** [comment]
we can put a credit link back if needed. we may also move these images to a dedicated location soon now that they are finalized ... :-)
