### ISSUE TITLE
Transcribe: Common Misconceptions

### ISSUE THREAD

**Issue by mihi-tr** [okfn/handbook#45]
Transcribe the following module to restructured text.

Instructions here: https://github.com/okfn/datawrangling/wiki/Tutorial-Sprint
Module: https://docs.google.com/document/d/1_bAgVYeQugi0mXAIf2WWtxbhgWTPBi2ZES1pgd8vX3w/edit#

**Comment by aabril** [comment]
Could assign myself this one?
This would be the first transcription I do, but I'm familiarized with Restructured text and Git.

**Comment by mihi-tr** [comment]
Great thanks! Consider yourself assigned...
