### ISSUE TITLE
Transcribe: Tell me a Story

### ISSUE THREAD

**Issue by mihi-tr** [okfn/handbook#46]
Transcribe the following module to restructured text.

Instructions here: https://github.com/okfn/datawrangling/wiki/Tutorial-Sprint
Module: https://docs.google.com/document/d/1pi8UnLNBj6wpFtLYWc98_jGBgRfk1WaZsZbpPO-XViE/edit#heading=h.8fik7l520kzj

**Comment by DuarteRV** [comment]
I've never done a transcription before but I'd like to give it a try.

**Comment by mihi-tr** [comment]
Go ahead! If you need help, just email schoolofdata or me

**Comment by mihi-tr** [comment]
Thanks @DuarteRV (misspelled your name in the commit message :/)
