### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by optikfluffel** [okfn/handbook#5]
Hey :)
Could I try to add some more design-stuff including a logo to this project?

**Comment by timClicks** [comment]
+1 from me

**Comment by pudo** [comment]
Amazing! I quite like the simple flask layout but I think a more specific logo would be great!

**Comment by optikfluffel** [comment]
What do you think about that (a first try to make a logo)?
![DataPatterns.org Logo](http://udokramer.com/datapatterns.png)

**Comment by timClicks** [comment]
I like the concept, maybe turn it into a tripartite logo with docs on
the left, comp in middle and a graph on right?

For some reason, the bar & line graph looks like an angry face to me.

**Comment by optikfluffel** [comment]
How about one of these?

![DataPatterns.org Logo 2](http://udokramer.com/datapatterns2.png)
![DataPatterns.org Logo 3](http://udokramer.com/datapatterns3.png)

http://udokramer.com/datapatterns2.png
http://udokramer.com/datapatterns3.png

**Comment by timClicks** [comment]
I think the first one is great

**Comment by rufuspollock** [comment]
Closing as this has now been integrated into the site -- see http://datapatterns.org/.

@optikfluffel: wanted to say a really big thank-you and ask what form of credit you would like on the site or in the README ...

**Comment by optikfluffel** [comment]
in the README would be cool :)
