### ISSUE TITLE
Convert original content from rst to markdown and insert

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook#69]
Want content from point where we were still patterns (?)
- This seems a likely point: https://github.com/okfn/datapatterns/tree/03892701946f3809e9eea3ad3a517f38e3600e04
- Alternately we can go off master HEAD and just use the recipes - https://github.com/okfn/datapatterns/tree/master/text/recipes

Once we have identified content we need to port across each file as one pattern - inherit from pattern layout #71 and put in pattern directory - #70.

For conversion suggest using pandoc.

**Comment by mihi-tr** [comment]
I do think this is a very interesting idea to bring back to life. We've turned this completely around with the School of Data stuff and we don't have a catalog for programmers and advanced data geeks on these issues. 

do we have good user stories yet for it?

Also: I do think this seems a good point to start from. Alternatively: Find my first commit and take it before that :)

**Comment by rufuspollock** [comment]
@mihi-tr what i have here atm is basically the first commit to the repo (the front page) converted to jekyll. IMO it is worth pulling in more than that (either of those points would be fine with me ... - i just don't if we lost recipes / patterns along the way)

Re user stories: I think have the short purpose statement (you just wrote one) is really valuable and I think we are close to that - not sure if we need full user stories (but would def be nice to have if you'd like to have a stab!)

**Comment by rufuspollock** [comment]
@mihi-tr ^^^ - would you be up for helping boot this up generally?

**Comment by mchelen** [comment]
I'm going to try converting some of the .rst files using pandoc, and see if they need manual cleanup after conversion.

**Comment by rufuspollock** [comment]
@mchelen how did you get on here? @todrobbins is going to have a stab.

@todrobbins - i think #71 and #70 are now in a good enough state to guide work here.

**Comment by rufuspollock** [comment]
@todrobbins do the references in description to places in the repo history make sense?

**Comment by rufuspollock** [comment]
@todrobbins @seralf - thoughts here? Any progress?

**Comment by seralf** [comment]
Hi I've made some simple conversion with pandoc, but I stopped because
reading the comments I thought this step was already done, and I was not
sure what is still required.
Are the first retext -> markdown draft already shared somewhere? (on a
specific fork/branch?): I ask in order to avoid work on the same files...
if it could be useful I could start forking the original files, replacing
them one by one on the fork (for example using a specific branch) and pull
them back.

2015-05-10 19:39 GMT+02:00 Rufus Pollock notifications@github.com:

**Comment by rufuspollock** [comment]
@seralf no the conversion has not been done so please dive in - and great you are already doing this. You want to commit this stuff straight into the HEAD of gh-pages branch using the structure in #71 and #70

**Comment by rufuspollock** [comment]
@seralf how are you doing - excited to see this in

**Comment by todrobbins** [comment]
Thanks for taking this on @seralf! I thought I'd be able to do it but my workload changed recently. Cheers!

**Comment by seralf** [comment]
Hi I've created a new branch called `editing-markdown` in my fork, and the make a pull request containing some really raw and initial experiments for rewriting:
https://github.com/seralf/datapatterns/tree/editing-markdown

There are several formattings which doesn't make sense in markdown, and we have to find a good alternative, depending on the processor (and relative extension) used for rendering. Please consider some weird format I've adopted just as a placeholder at the moment: if the general outline could work, I can proceed on `/recipes` too, and then we can have a good base to apply all the layouts, metadata, and so on.

BTW reading the contents I wonder if after this rewrites I could send some text for contributing to the linked data and search part. Is it possible to contribute in some way?
Do you have plans for converting the book on epbub? this could be a nice option.
(sorry if I go OT here :-) )

**Comment by rufuspollock** [comment]
@seralf commented in the pull request. We definitely want new content and linked data stuff would be very welcome.

**Comment by seralf** [comment]
ok thanks, if we can find the best way to update the formatting with
markdown, I'll eventually try to add some draft in that direction (the free
time is poor, so one step at time :-) ). Thank you.

2015-05-15 9:20 GMT+02:00 Rufus Pollock notifications@github.com:

**Comment by rufuspollock** [comment]
@seralf great work in #78. I would say next steps are the following:
- move "patterns" to top level directory as per our site architecture in #70
- move all patterns to follow site architecture in #70 and have correct front matter see #71  
  - i.e. we want `/pattern/name-of-pattern/index.md`
- move `/text/` items to either be patterns or top level (front page)
  - index.md and intro.md can both move into top-level index.md (i.e. site front page) - everything else can be patterns
  - glossary is special and go at site root i.e. `/glossary/index.md`(note glossary seems to be duped in two locations atm)

Are you up for doing this?

**Comment by seralf** [comment]
Yes Rufus, sorry for not correcting yet the headers for yekill: I had some
other things to manage in the last weeks that ruins all my plans for spare
time :-(
During the next week I hope to be able to follow your list and move on the
required updates. I also have some suggestion for addition or normalization
of formatting, but I left them after a first good version in this format.
If you want I could write them in some text file as a note, for the moment,
so we have some trace of them: most are unregular formatting I found
following different pages...

2015-06-21 14:30 GMT+02:00 Rufus Pollock notifications@github.com:

**Comment by rufuspollock** [comment]
@seralf sounds great! Re formatting either you can do that as you go or you could open a new issue where you log issues and we come back to that later.

**Comment by seralf** [comment]
ok then, I'll update as soon as i can be able to work on this.
for reformatting I tried to avoid changing too much the current format
before discussing it, but if we are free, I could try to make the various
part a bit more homogeneus where possible, it could help for readability,
and eventually give back some sort of light lineguides for future
contributions. Just an idea: I worked a lot on publishing things with
multiple authors in the past and while give them too much constraint is
really bad, it is also helpful to have some kind of minimal outline :-)

2015-06-21 15:02 GMT+02:00 Rufus Pollock notifications@github.com:

**Comment by rufuspollock** [comment]
@seralf **great** suggestion re having some kind of standard structure for patterns - both existing and especially ne wones. I think you are absolutely right that we want some "contraints" / guidance here so big +1 on this suggestion and please take a lead on this if you would like :-)

**Comment by danfowler** [comment]
As this conversion step has already been done, I am closing in favor of the next organizational #79 and styling #80 steps.

**Comment by seralf** [comment]
great! :-)

2015-10-14 14:30 GMT+02:00 Daniel Fowler notifications@github.com:
