### ISSUE TITLE
Site Info (URL) Architecture

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook#70]
Suggest

```
/ - home page and list of patterns
/pattern/{pattern-title-as-slug}.md
/contribute/ # instructions for contribution
```

We also need to turn on `pretty_permalinks` in `_config.yml`
## Discussed but won't do

```
/ - home page and list of patterns
# digit id (increasing incrementally from first) is to have a convenient shorthand e.g. data pattern no 3
# /pattern/{digit-id}-{pattern-title-as-slug}/
```

**Comment by mihi-tr** [comment]
do we need the `{digit-id}` ?  wouldn't a slug be enough?

**Comment by rufuspollock** [comment]
I thought digit-id is nice because you could refer to pattern by their number e.g. data pattern no.3 :-)

**Comment by rufuspollock** [comment]
@mihi-tr you around? would you be up for contributing here?

**Comment by rufuspollock** [comment]
@mihi-tr any thoughts further here? Will you have a chance to contribute?

**Comment by mihi-tr** [comment]
Sorry tied up right now. Will take a look when I do find time.

**Comment by rufuspollock** [comment]
@mihi-tr no problem - any idea when you will have time (1 week, 1 month, 1 year ;-0 ...)

**Comment by rufuspollock** [comment]
OK, removing the digital-id stuff (updated issue description). I think this now good enough to go.

**Comment by rufuspollock** [comment]
FIXED.

**Comment by rufuspollock** [comment]
Reopen as we need to still implement this e.g. ref #79
