### ISSUE TITLE
(Nice) Site Theme

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook#72]
Be good to keep the basic bootstrap but could we make this "nice"

**Comment by rufuspollock** [comment]
@pudo you have skillz in this area - would you be up for having a go at this (+ the related #71)

**Comment by pudo** [comment]
I think I need to limit my battles :smile: - datapatterns would be a cool thing if we could do it properly, but as a weekend thing I'm going to resist for now...

**Comment by rufuspollock** [comment]
Suggest we use new open data handbook theme.

**Comment by rufuspollock** [comment]
@seralf what do you reckon of working on this - as i said all you need to do is copy and paste over from https://github.com/openspending/dotorg

/cc @danfowler @mintcanary - this is another place we are applying the theme

**Comment by rufuspollock** [comment]
@seralf any thoughts here? Would be lovely to get this updated :-)

**Comment by seralf** [comment]
hi Rufus, sorry for not replying but i had a lot of annoying issues in the
past days/weeks...

the example template looks fine!
hopefully I will be able to look at this again during this week

2015-09-10 16:41 GMT+02:00 Rufus Pollock notifications@github.com:

**Comment by danfowler** [comment]
@seralf I can help if you run into any issues :sos:

**Comment by seralf** [comment]
Thanks Daniel, it would be great to have some help on this! :-)

2015-09-14 7:13 GMT+02:00 Daniel Fowler notifications@github.com:

**Comment by danfowler** [comment]
:) Anything in particular blocking?

**Comment by seralf** [comment]
I had very few time to study how to put jekyll in place sadly, due to other
things to manage. If you have experience with that and you can prepare the
template for one of the page I could find the time to handle the others in
the same way: I know it should be not a complex task at this level. I'll
try to get back working on this in these days, if hopefully I will have not
other mishaps :-)

2015-09-17 9:38 GMT+02:00 Daniel Fowler notifications@github.com:

**Comment by danfowler** [comment]
Hi @seralf I put a template in place and some basic layout (http://datapatterns.org/), so I'll close this ticket. What's left is some cleanup of the content and maybe some new graphics (currently reusing background logo from another project). Would you be interested in taking that on?

**Comment by seralf** [comment]
yes of course!
I was distracted by other things and even if I can work slowly on this, if
I can contribute to anything from template to content, just let me know,
I'm glad to help.

(sorry for not helping much lately)

2015-10-14 10:11 GMT+02:00 Daniel Fowler notifications@github.com:

**Comment by danfowler** [comment]
Hey, @seralf no worries :smile: 

I've made a couple of small issues to work on: https://github.com/okfn/datapatterns/issues/80 and https://github.com/okfn/datapatterns/issues/79
