### ISSUE TITLE
Move "patterns" to top level directory as per our site architecture in #70

### ISSUE THREAD

**Issue by danfowler** [okfn/handbook#79]
Patterns have now been converted and now must be re-organized under `/pattern/` (i.e. some are still under `/pattern/patterns/` and should be moved under `/pattern/`).

Glossary is special and go at site root i.e. `/glossary.md` (actual URL path will be `/glossary/`) (note glossary seems to be duped in two locations atm)

**Comment by gsilvapt** [comment]
@danfowler Should files be replaced, renamed or something else?

**Comment by rufuspollock** [comment]
@gsilvapt everything should move up to live under pattern. Can i suggest you post a short summary of what you plan to do here before you do it -- this is a generally recommended workflow.

e.g.
- I will move x to y
- Create file y

**Comment by gsilvapt** [comment]
In order to move the files under `/patterns/patterns`, some have the same name and you'll have a prompt asking if you want it to ignore those, rename or replace. My question was which one do you prefer to do in this case.

List of files with the same filename:
- geocoding.md
- index.md
- liberating-html-tables.md

I can check the contents of each file to see if it is just a repetition or if the contents differ between files.

**Comment by rufuspollock** [comment]
@gsilvapt have you looked at the difference between these - are they just the same file. Also see #70 for site infor architecture. Please go ahead and do a first sample pull request showing what you plan to do.

**Comment by gsilvapt** [comment]
I was looking into all repeated files and:
- `index.md` is different in both ends. Under `/patterns/patterns` it seems like a glossary, while the one under `/patterns/` is an introductiory file. Also, `patterns/index.md` has as title `Recipes`. Should filename be changed to `recipes.md` or `patterns.md` ?
- `/patterns/geocoding.md` is about how to geocode data in spreadsheets, while `/patterns/patterns/geocoding.md` is about a script called _Geo-Googledocs_ allowing the user to export to `GeoJSON` and `GEOcode` arbitrary addresses.
  I'd suggest changing the `/patterns/patterns/geocoding.md` filename to `geo-googledocs.md`
- Finally, `liberating-html-tables.md` is actually the same file. `patterns/patterns/liberating-html-tables.md` is more complete, so I will replace the file in the parent directory, if you allow me.

Hope this helps! Sorry if I am not being too independent here but I prefer asking than doing things we will struggle to fix!

**Comment by gsilvapt** [comment]
The [pull request 83](https://github.com/okfn/datapatterns/pull/83) will go as follows:
- [x] Move `/patterns/glossary.md` to (new) `glossary` directory - there is still another glossary under `pattern/appendix/`
- [x] Merging `liberating-html-tables.md` in `patterns/patterns/liberating-html-tables.md` and `/patterns/liberating-html-tables.md`
- [x] Changing filenames as suggested in previous comment.
- [x] Move non-repeated files from `/patterns/patterns/` to parent directory
- [x] Delete parent `/pattern/pattern` directory

Let me know what I can do to improve this and if this current structure solves this issue.
Also, please have a look at the email print I sent with the PR just to ensure everything is correct and working.

**Comment by gsilvapt** [comment]
FIXED.
