### ISSUE TITLE
Tutorial: Contributing to Core Datasets

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook#90]
- [ ] Intro to Data Packages - can reference FrictionlessData.io
- [ ] Details of core datasets project
- [ ] Walkthrough of packaging a dataset in the "right way"

@gsilvapt creating this to detail what we have on this site vs frictionlessdata.io. I think we can make this a top priority.

---

Considering the structure proposed in issue #94, the following pages should be created/get resources from the corresponding pages:
- `/core-datasets/` - maybe just use https://github.com/okfn/okfn.github.com/blob/master/blog/_posts/2015-01-03-data-curators-wanted-for-core-datasets.md 
- `/core-datasets/guide/` - core data curators guide - copy this over from https://github.com/okfn/data.okfn.org-new/blob/master/doc/core-data-curators.md 
  and then start merging Gustavo’s material from e.g. http://okfnlabs.org/handbook/core-guides/core-data-curators/ and get started etc

**Comment by gsilvapt** [comment]
I think this issue is done, even though we will need to go through it again in a later stage?

**Comment by rufuspollock** [comment]
As per https://github.com/okfn/handbook/issues/89#issuecomment-218984163 i am re-opening. Please link to pages that resolve and we can close.

**Comment by gsilvapt** [comment]
This link guides you through the process of creating a data package: http://okfnlabs.org/handbook/core-guides/core-data-curators/

**Comment by rufuspollock** [comment]
@gsilvapt great progress.

Some thoughts:

Existing material. We already have:
- http://data.okfn.org/doc/core-data-curators 
  - Source here: https://github.com/okfn/data.okfn.org-new/blob/master/doc/core-data-curators.md
- And http://data.okfn.org/roadmap/core-datasets
  - https://github.com/okfn/data.okfn.org-new/blob/master/views/core-datasets.html

I would suggest we port these over first (**unchanged**). So we would have:

```
# index page is basically https://github.com/okfn/data.okfn.org-new/blob/master/views/core-datasets.html
/handbook/core-datasets/

# content of https://github.com/okfn/data.okfn.org-new/blob/master/doc/core-data-curators.md
/handbook/core-datasets/guide/

# move your current content e.g. http://okfnlabs.org/handbook/core-guides/core-data-curators/ to this location
/handbook/core-datasets/preparing-data/
```

In general, worth setting out this kind of info architecture yourself in advance of implementation so we can do a quick check before we dive in.

**Comment by gsilvapt** [comment]
Considering the structure proposed in issue #94, the following pages should be created/get resources from the corresponding pages:

* `/core-datasets/` - maybe just use https://github.com/okfn/okfn.github.com/blob/master/blog/_posts/2015-01-03-data-curators-wanted-for-core-datasets.md 

* `/core-datasets/guide/` - core data curators guide - copy this over from https://github.com/okfn/data.okfn.org-new/blob/master/doc/core-data-curators.md 
 and then start merging Gustavo’s material from e.g. http://okfnlabs.org/handbook/core-guides/core-data-curators/ and get started etc

**Comment by rufuspollock** [comment]
@gsilvapt i suggest moving this update into the main description of the issue and then deleting your comment.

**Comment by gsilvapt** [comment]
Closing issue as it has been fixed, only small improvements may be needed in terms of English.

FIXED.
