### ISSUE TITLE
Home page design

### ISSUE THREAD

**Issue by gsilvapt** [okfn/handbook#95]
It is crucial to discuss how the homepage should look like.

**Comment by rufuspollock** [comment]
@gsilvapt great. Comments:
- Issue title is surely: "Home page design" or similar (`index.html` is the file name and could be one of many files named `index.html`)
- Do you have a suggestion for what we should have here 
- How is this different from #84 - it seems to me this is probably just a duplicate. If so we should close this  with comment `DUPLICATE of #84`

**Comment by gsilvapt** [comment]
This is was more related to the design of the page (what goes where, texts to insert where, etc) but yea, this is pretty much duplicate because we can discuss this in #84.

DUPLICATE OF #84
